# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moge_web', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 2, 21, 8, 28, 8, 68375, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
